//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5.1")]
        public string verInfo {
            get {
                return ((string)(this["verInfo"]));
            }
            set {
                this["verInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tlcScheduleStartRow {
            get {
                return ((int)(this["tlcScheduleStartRow"]));
            }
            set {
                this["tlcScheduleStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cnsweComStartRow {
            get {
                return ((int)(this["cnsweComStartRow"]));
            }
            set {
                this["cnsweComStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cnsweStartTime {
            get {
                return ((string)(this["cnsweStartTime"]));
            }
            set {
                this["cnsweStartTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dcComStartRow {
            get {
                return ((int)(this["dcComStartRow"]));
            }
            set {
                this["dcComStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dcScheduleStartRow {
            get {
                return ((int)(this["dcScheduleStartRow"]));
            }
            set {
                this["dcScheduleStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dcSchedulePath {
            get {
                return ((string)(this["dcSchedulePath"]));
            }
            set {
                this["dcSchedulePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultOpenLocation {
            get {
                return ((string)(this["defaultOpenLocation"]));
            }
            set {
                this["defaultOpenLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultSaveLocation {
            get {
                return ((string)(this["defaultSaveLocation"]));
            }
            set {
                this["defaultSaveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tlcComStartRow {
            get {
                return ((int)(this["tlcComStartRow"]));
            }
            set {
                this["tlcComStartRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tlcSchedulePath {
            get {
                return ((string)(this["tlcSchedulePath"]));
            }
            set {
                this["tlcSchedulePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dcConditionStartIndex {
            get {
                return ((int)(this["dcConditionStartIndex"]));
            }
            set {
                this["dcConditionStartIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dcConditionLength {
            get {
                return ((int)(this["dcConditionLength"]));
            }
            set {
                this["dcConditionLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tlcConditionStartIndex {
            get {
                return ((int)(this["tlcConditionStartIndex"]));
            }
            set {
                this["tlcConditionStartIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tlcConditionLength {
            get {
                return ((int)(this["tlcConditionLength"]));
            }
            set {
                this["tlcConditionLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string transistionType {
            get {
                return ((string)(this["transistionType"]));
            }
            set {
                this["transistionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string transistionDuration {
            get {
                return ((string)(this["transistionDuration"]));
            }
            set {
                this["transistionDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useTransistion {
            get {
                return ((bool)(this["useTransistion"]));
            }
            set {
                this["useTransistion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dcIDSchedulePath {
            get {
                return ((string)(this["dcIDSchedulePath"]));
            }
            set {
                this["dcIDSchedulePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tlcdcRusAudioExtension {
            get {
                return ((string)(this["tlcdcRusAudioExtension"]));
            }
            set {
                this["tlcdcRusAudioExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tlcdcEstAudioExtension {
            get {
                return ((string)(this["tlcdcEstAudioExtension"]));
            }
            set {
                this["tlcdcEstAudioExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tlcdcUseRusAudios {
            get {
                return ((bool)(this["tlcdcUseRusAudios"]));
            }
            set {
                this["tlcdcUseRusAudios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dcidFindWord {
            get {
                return ((string)(this["dcidFindWord"]));
            }
            set {
                this["dcidFindWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dcidReplaceWord {
            get {
                return ((string)(this["dcidReplaceWord"]));
            }
            set {
                this["dcidReplaceWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useFindReplace {
            get {
                return ((bool)(this["useFindReplace"]));
            }
            set {
                this["useFindReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dcIDUseAudioExtension {
            get {
                return ((bool)(this["dcIDUseAudioExtension"]));
            }
            set {
                this["dcIDUseAudioExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dcIDAudioExtension {
            get {
                return ((string)(this["dcIDAudioExtension"]));
            }
            set {
                this["dcIDAudioExtension"] = value;
            }
        }
    }
}
